### ISSUE TITLE
Missing `next_marker` in `Items`

### ISSUE THREAD

**Issue by tobihagemann** [box/box-swift-sdk-gen#122]
### Is your feature request related to a problem? Please describe.

When listing items in a folder, you get an `Items` object as a reponse. And this object doesn't contain the `next_marker` property.

### Describe the solution you'd like

I'd like the `Items` object to include the optional `next_marker` for marker-based pagination.

### Describe alternatives you've considered

I don't think that there is an alternative, but maybe I didn't understand how to do marked-based pagination with this library.

### Additional context

https://github.com/box/box-swift-sdk-gen/blob/d0a7adb201c823313f0a5de25fa4fc5469590c97/Sources/Schemas/Items/Items.swift
https://developer.box.com/reference/get-folders-id-items/
https://developer.box.com/guides/api-calls/pagination/marker-based/

**Comment by congminh1254** [comment]
Hi @tobihagemann

Thanks for using this new Box Swift SDK Gen. I can see that `next_marker` field is missing in the [API specification](https://developer.box.com/reference/resources/items/). I will work with others team to add this field as soon as possible.

Bests,
Minh

**Comment by tobihagemann** [comment]
I've seen that this was fixed in b186b11a2c591cd4fdd3b50733750a7bb4ec94e9. Would it be possible for you to create a new tag? 😅 Would really help us a lot, so that we can finish our Box integration without forking this project.

**Comment by arjankowski** [comment]
Hi @tobihagemann,

We have just released version `0.3.0` as you requested :) and we hope you'll like it ❤️

From now on, each new version will no longer include the `v` prefix, as per Apple's recommendation on this matter: https://developer.apple.com/documentation/xcode/publishing-a-swift-package-with-xcode#Tag-your-latest-commit.

Best regards,
Artur
